package:
  name: cavapy
  version: 0.1.0

source:
  path: ..  # This points to the parent directory where climate.py and setup.py are located

requirements:
  run:
    - conda-forge::xclim=0.53.2
    - conda-forge::netcdf4=1.7.2
    - conda-forge::geopandas=0.14.4

about:
  home: https://github.com/Risk-Team/cavapy/tree/main
  license: MIT
  summary: "A Python library to facilitate access to CAVA data"
  description: |
    This package facilitates downloading CORDEX-CORE model data.
  dev_url: https://github.com/Risk-Team/cavapy/tree/main

channels:
   - conda-forge
   - default

extra:
  recipe-maintainers:
    - RSO9192
    - olokshyn

