package:
  name: cava_data               # Name of your package
version: 0.1.0                # Version of your package

source:
  path: ..                      # Path to your project folder (relative to `recipe/`)

build:
  noarch: python                # For architecture-independent Python packages
number: 0                     # Build number (increment for updates)
script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
  - python >=3.6             # Minimum Python version
- pip                       # Needed to install your package
run:
  - python >=3.6             # Runtime dependency
- xclim ==0.53.2            # Dependency from Conda-Forge
- netcdf4 ==1.7.2           # Dependency from Conda-Forge
- geopandas ==0.14.4        # Specific version of geopandas

about:
  home: https://github.com/Risk-Team/cava_data/tree/main  # URL for the project (GitHub)
license: MIT
summary: "A Python library to facilitate access to CAVA data"
description: |
  This package facilitates downloading CORDEX-CORE model data for use in climate risk analysis.
dev_url: https://github.com/Risk-Team/cava_data/tree/conda  # Optional: link to development info

extra:
  recipe-maintainers:
  - RSO9192
  - olokshyn
